/**
 * CT Brain complete-report formats — curated verbatim from the doctor's own
 * CT report library (care-erp docs/report-formats/ct). Language kept verbatim
 * (spelling normalized); every row occupies a semantic slot so phrase-chip
 * additions replace, never duplicate.
 */
import type { FormatSeed, FormatRowSeed } from "@/lib/seedData";

const T = {
  ncct: "Serial transaxial scans were performed starting from the base of skull in the infratentorial and supratentorial compartment.",
  cect: "NCCT followed by CECT of head by taking (5 x 5 mm) axial sections from the base of skull up to the vertex.",
};

const REC = "Clinico-pathological correlation. Not for medico-legal purpose.";

const R = (
  concept: string,
  text: string,
  extra: Partial<FormatRowSeed> = {},
): FormatRowSeed => ({ region: "CT Head", concept, text, inImpression: false, ...extra });

/** Normal-impression line — auto-yields when a real finding enters the impression. */
const NI = (): FormatRowSeed => ({
  region: "CT Head", concept: "normal_impression", text: "No significant abnormality detected.",
  inImpression: true, impressionOnly: true,
});

/** The doctor's NCCT normal scaffold (his exact lines, in his exact order). */
const NORMAL_SCAFFOLD = (ce = false): FormatRowSeed[] => {
  const e = ce ? " and enhancement" : "";
  return [
    R("parenchyma", `Bilateral cerebral hemispheres are normal in attenuation${e}.`),
    R("deep_gray", `Bilateral basal ganglia and thalamus are normal in attenuation${e}.`),
    R("posterior_fossa", `Posterior fossa structures are normal in attenuation${e}.`),
    R("sulci", "Cortical sulci and sylvian fissures are normal."),
    R("ventricles", "Ventricular system is normal."),
    R("midline", "Falx is central."),
    R("extra_axial", "There is no extra-axial collection."),
    R("calvarium", "Bony calvarium is intact."),
  ];
};

export const CT_BRAIN_FORMATS: FormatSeed[] = [
  {
    key: "ct-head-ncct-normal", modality: "CT", region: "CT Head",
    name: "Normal (NCCT)", studyTitle: "NCCT BRAIN", titleSuffix: "",
    technique: T.ncct, recommendation: REC, isNormal: true, sortOrder: 1,
    rows: [...NORMAL_SCAFFOLD(), NI()],
  },
  {
    key: "ct-head-cect-normal", modality: "CT", region: "CT Head",
    name: "Normal (CECT)", studyTitle: "CECT BRAIN", titleSuffix: "",
    technique: T.cect, recommendation: REC, isNormal: true, sortOrder: 2,
    rows: [...NORMAL_SCAFFOLD(true), NI()],
  },
  {
    key: "ct-head-senile-atrophic", modality: "CT", region: "CT Head",
    name: "Senile Atrophic Changes", studyTitle: "NCCT BRAIN",
    titleSuffix: "senile atrophic changes",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 3,
    rows: [
      R("parenchyma", "Bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      // Same slots as the normal lines — prominence replaces
      R("sulci", "Cortical sulci and sylvian fissures are prominent.", { inImpression: true }),
      R("ventricles", "Ventricular system is prominent.", { inImpression: true }),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact. No obvious bony fracture is seen."),
    ],
  },
  {
    key: "ct-head-early-senile", modality: "CT", region: "CT Head",
    name: "Early Senile Changes", studyTitle: "NCCT BRAIN",
    titleSuffix: "early senile atrophy",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 4,
    rows: [
      R("parenchyma", "Bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("sulci", "Prominent cortical sulci and sylvian fissure.", { inImpression: true }),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Focal calcification of falx. Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact. No obvious bony fracture is seen."),
    ],
  },
  {
    key: "ct-head-cerebral-atrophy", modality: "CT", region: "CT Head",
    name: "Cerebral Atrophy", studyTitle: "NCCT BRAIN",
    titleSuffix: "cerebral atrophy",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 5,
    rows: [
      R("sulci", "Bilateral sylvian fissure, cortical sulci, basal cisterns, quadrigeminal cistern, prepontine cistern and cisterna magna are prominent. CSF pockets are seen in interhemispheric fissure in frontal region.", { inImpression: true }),
      R("parenchyma", "Bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("calvarium", "Bony calvarium is intact. No obvious bony fracture is seen."),
    ],
  },
  {
    key: "ct-head-acute-mca-infarct", modality: "CT", region: "CT Head",
    name: "Acute Infarct (MCA Territory)", studyTitle: "NCCT BRAIN",
    titleSuffix: "acute infarct (mca territory)",
    technique: T.ncct, recommendation: "Clinico-pathological correlation. Follow-up scan.", isNormal: false, sortOrder: 6,
    rows: [
      R("infarct", "A wedge shaped low density area involving both grey and white matter in the left middle cerebral artery territory. S/O Acute infarct (Evolving).", { inImpression: true }),
      R("sulci", "Right cortical sulci and sylvian fissures are normal."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact. No obvious bony fracture is seen."),
    ],
  },
  {
    key: "ct-head-chronic-infarct", modality: "CT", region: "CT Head",
    name: "Chronic Infarct (Encephalomalacia)", studyTitle: "NCCT BRAIN",
    titleSuffix: "chronic infarct",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 7,
    rows: [
      R("infarct_chronic", "Encephalomalacic area is seen in right fronto-parietal lobe involving the right sylvian fissure, anterior half of right insular cortex and external capsule. Similar smaller area in right occipital lobe.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Rest of the basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("sulci", "Rest of the cortical sulci and left sylvian fissure is normal."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact. No obvious bony fracture is seen."),
    ],
  },
  {
    key: "ct-head-lacunar-senile", modality: "CT", region: "CT Head",
    name: "Lacunar Infarcts + Senile Atrophy", studyTitle: "NCCT BRAIN",
    titleSuffix: "lacunar infarcts and senile atrophy",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 8,
    rows: [
      R("parenchyma", "Bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Lacunar infarcts in bilateral basal ganglia involving bilateral thalamus and bilateral caudate nucleus. Fine foci of calcification in bilateral basal ganglia.", { inImpression: true }),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("sulci", "Prominent bilateral cortical sulci and sylvian fissure.", { inImpression: true }),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact. No obvious bony fracture is seen."),
    ],
  },
  {
    key: "ct-head-acute-iph-ivh", modality: "CT", region: "CT Head",
    name: "Acute IPH with IV Extension", studyTitle: "NCCT BRAIN",
    titleSuffix: "acute intraparenchymal haemorrhage",
    technique: T.ncct, recommendation: "Clinico-pathological correlation.", isNormal: false, sortOrder: 9,
    rows: [
      R("hemorrhage", "Hyperdense areas of blood densities in bilateral basal ganglia region (Right 4.8 x 4.0 x 2.2 cm; Left 7.0 x 4.2 x 2.0 cm) involving external capsule, lentiform nucleus, parts of anterior and posterior limbs of internal capsule — S/O Acute intraparenchymal haemorrhage with surrounding oedema and mass effect as evident by effacement of bilateral cortical sulci and sylvian fissure.", { inImpression: true }),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("ventricles", "Ventricular system is effaced. Hyperdense area of blood density in left occipital horn.", { inImpression: true }),
      R("midline", "Falx is central."),
      R("calvarium", "Bony calvarium is intact. No obvious bony fracture is seen."),
    ],
  },
  {
    key: "ct-head-acute-sdh", modality: "CT", region: "CT Head",
    name: "Acute SDH + SAH", studyTitle: "NCCT BRAIN",
    titleSuffix: "acute subdural haematoma",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 10,
    rows: [
      R("hemorrhage", "There is evidence of hyperdense crescent shaped collection (measures 7.0 x 5.0 x 0.9 cm) along the concavity of the left fronto-parietal bone — S/O Acute subdural haematoma with mass effect as evident by effacement of adjacent cortical sulci and sylvian fissure with midline shift of 0.6 cm towards right.", { inImpression: true }),
      R("sah", "Hyperdense area of blood density is also seen in the interhemispheric fissure and few cortical sulci in high parietal region and bilateral sylvian fissures — S/O Acute subarachnoid haemorrhage.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation."),
      R("ventricles", "Ventricular system is normal."),
      R("fracture", "Linear undisplaced fracture of the right temporal bone.", { inImpression: true }),
      R("soft_tissue", "Soft tissue swelling in right temporo-parietal region.", { inImpression: true }),
    ],
  },
  {
    key: "ct-head-acute-edh", modality: "CT", region: "CT Head",
    name: "Acute EDH + Contusion", studyTitle: "NCCT BRAIN",
    titleSuffix: "acute extradural haematoma",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 11,
    rows: [
      R("hemorrhage", "A well defined biconvex hyperdense collection of blood density along the concavity of fronto-parietal bone — S/O Acute extradural haematoma (5.0 x 0.9 cm).", { inImpression: true }),
      R("contusion", "A small contusion in right frontal lobe.", { inImpression: true }),
      R("parenchyma", "Bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("sulci", "Cortical sulci and sylvian fissures are normal."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("fracture", "Hair line fracture of the right frontal bone.", { inImpression: true }),
      R("soft_tissue", "Soft tissue swelling in right high fronto-parietal region.", { inImpression: true }),
    ],
  },
  {
    key: "ct-head-haemorrhagic-contusion", modality: "CT", region: "CT Head",
    name: "Haemorrhagic Contusion", studyTitle: "NCCT BRAIN",
    titleSuffix: "haemorrhagic contusion",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 12,
    rows: [
      R("contusion", "Acute haemorrhagic contusion (1.1 x 0.9 cm) with minimal surrounding oedema in left temporo-parietal lobe.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("sulci", "Cortical sulci and sylvian fissures are normal."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("fracture", "Hair line fracture of the left temporal bone.", { inImpression: true }),
      R("soft_tissue", "Soft tissue swelling in left periorbital region and left temporo-parietal region.", { inImpression: true }),
    ],
  },
  {
    key: "ct-head-contusion-edh-mass-effect", modality: "CT", region: "CT Head",
    name: "Contusion + EDH with Mass Effect", studyTitle: "NCCT BRAIN",
    titleSuffix: "haemorrhagic contusion with extradural haematoma",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 13,
    rows: [
      R("contusion", "Acute haemorrhagic contusion (2.1 x 1.8 cm) with surrounding oedema in left temporo-parietal lobe with mass effect as evident by effacement of adjacent cortical sulci and sylvian fissure and midline shift of 0.4 cm towards right.", { inImpression: true }),
      R("hemorrhage", "A small acute extradural haematoma (6.1 x 1.0 cm) along the concavity of the right temporal bone.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Rest of the bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("ventricles", "Ventricular system is normal."),
      R("fracture", "Hair line fracture of the right temporal bone.", { inImpression: true }),
      R("soft_tissue", "Soft tissue swelling in right temporo-parietal region.", { inImpression: true }),
    ],
  },
  {
    key: "ct-head-acute-ich-sah", modality: "CT", region: "CT Head",
    name: "Acute ICH + SAH", studyTitle: "NCCT BRAIN",
    titleSuffix: "acute intracerebral haemorrhage with subarachnoid haemorrhage",
    technique: T.ncct, recommendation: "Clinico-pathological correlation.", isNormal: false, sortOrder: 14,
    rows: [
      R("hemorrhage", "An ill defined hyperdense area of blood density (measures 5.0 x 4.7 x 3.1 cm) in the left occipital lobe with mild surrounding oedema — S/O Acute intracerebral haemorrhage.", { inImpression: true }),
      R("sah", "Hyperdense area of blood density is also seen in interhemispheric fissure and tentorium cerebelli on left side — S/O Subarachnoid haemorrhage.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("ventricles", "Ventricular system is normal."),
      R("calvarium", "Bony calvarium is intact. No obvious bony fracture is seen."),
    ],
  },
  {
    key: "ct-head-ncc-vesicular", modality: "CT", region: "CT Head",
    name: "NCC — Vesicular Stage", studyTitle: "CECT BRAIN",
    titleSuffix: "neurocysticercosis (vesicular stage)",
    technique: T.cect, recommendation: REC, isNormal: false, sortOrder: 15,
    rows: [
      R("ncc", "A well defined small cystic lesion with tiny internal hyperdense foci in right frontal cortex and another similar lesion in right temporal cortex. No surrounding oedema is present. No cyst wall enhancement on post contrast scan.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation and enhancement."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation and enhancement."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation and enhancement."),
      R("sulci", "Cortical sulci and sylvian fissures are normal."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact."),
    ],
  },
  {
    key: "ct-head-ncc-calcified", modality: "CT", region: "CT Head",
    name: "NCC — Multiple Calcified Granulomas", studyTitle: "CECT BRAIN",
    titleSuffix: "multiple calcified granulomas",
    technique: T.cect, recommendation: REC, isNormal: false, sortOrder: 16,
    rows: [
      R("ncc", "Multiple calcified granulomas in bilateral cerebral hemispheres, including basal ganglia. A well defined ring enhancing lesion with eccentric foci of calcification without surrounding perilesional oedema in right thalamus.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation and enhancement."),
      R("deep_gray", "Rest of the basal ganglia and thalamus are normal in attenuation and enhancement."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation and enhancement."),
      R("sulci", "Cortical sulci and sylvian fissures are normal."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact. No obvious bony fracture is seen."),
    ],
  },
  {
    key: "ct-head-tuberculoma", modality: "CT", region: "CT Head",
    name: "Ring Enhancing Lesion ? Tuberculoma", studyTitle: "CECT BRAIN",
    titleSuffix: "ring enhancing lesion ? tuberculoma",
    technique: T.cect, recommendation: REC, isNormal: false, sortOrder: 17,
    rows: [
      R("tuberculoma", "NCCT shows hypodense area in left centrum semiovale with a hyperdense ring shaped lesion. CECT shows an irregular ring enhancing lesion with surrounding oedema and mass effect as evident by effacement of adjacent cortical sulci.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation and enhancement."),
      R("deep_gray", "Rest of the bilateral basal ganglia and thalamus are normal in attenuation and enhancement."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation and enhancement."),
      R("sulci", "Rest of the cortical sulci and sylvian fissures are normal."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact."),
    ],
  },
  {
    key: "ct-head-ring-lesion-dd", modality: "CT", region: "CT Head",
    name: "Ring Lesion — Tuberculoma / Abscess / Mets", studyTitle: "CECT BRAIN",
    titleSuffix: "ring enhancing lesion",
    technique: T.cect, recommendation: REC, isNormal: false, sortOrder: 18,
    rows: [
      R("tuberculoma", "A focal round to lobulated thin walled, hyperdense ring shaped mildly enhancing mass lesion (1.5 x 1.0 cm) near the grey white junction in right centrum semiovale. There is marked surrounding perilesional oedema and mass effect as evident by effacement of adjacent cortical sulci.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation and enhancement."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation and enhancement."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation and enhancement."),
      R("sulci", "Rest of the cortical sulci and sylvian fissures are normal."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact."),
    ],
  },
  {
    key: "ct-head-tbm", modality: "CT", region: "CT Head",
    name: "TBM with Hydrocephalus", studyTitle: "NCCT BRAIN",
    titleSuffix: "hydrocephalus ? tubercular meningitis",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 19,
    rows: [
      R("granuloma", "A small calcified granuloma in right occipital lobe.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("sulci", "Cortical sulci and sylvian fissures are normal."),
      R("ventricles", "Dilated bilateral lateral, 3rd and 4th ventricles suggesting communicating hydrocephalus.", { inImpression: true }),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
    ],
  },
  {
    key: "ct-head-calcified-granuloma", modality: "CT", region: "CT Head",
    name: "Calcified Granuloma", studyTitle: "NCCT BRAIN",
    titleSuffix: "calcified granuloma",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 20,
    rows: [
      R("granuloma", "Calcified granuloma in left temporal lobe.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("sulci", "Cortical sulci and sylvian fissures are normal."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact. No obvious bony fracture is seen."),
    ],
  },
  {
    key: "ct-head-nph", modality: "CT", region: "CT Head",
    name: "? Normal Pressure Hydrocephalus", studyTitle: "NCCT BRAIN",
    titleSuffix: "ventricular dilatation ? normal pressure hydrocephalus",
    technique: T.ncct, recommendation: "Clinico-pathological correlation. MRI brain.", isNormal: false, sortOrder: 21,
    rows: [
      R("ventricles", "Bilateral lateral ventricle and third ventricle is dilated with prominent cortical sulci and sylvian fissure.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
    ],
  },
  {
    key: "ct-head-gliosis", modality: "CT", region: "CT Head",
    name: "Gliosis", studyTitle: "CECT BRAIN",
    titleSuffix: "gliosis",
    technique: T.cect, recommendation: "CE MRI brain. Not for medico-legal purpose.", isNormal: false, sortOrder: 22,
    rows: [
      R("gliosis", "Non enhancing low attenuation area adjacent to frontal horn of lateral ventricle is noted in left fronto-parietal region.", { inImpression: true }),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation and enhancement."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation and enhancement."),
      R("sulci", "Cortical sulci and sylvian fissures are normal."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact."),
    ],
  },
  {
    key: "ct-head-medulloblastoma", modality: "CT", region: "CT Head",
    name: "Posterior Fossa Mass ? Medulloblastoma", studyTitle: "CECT BRAIN",
    titleSuffix: "posterior fossa mass",
    technique: T.cect, recommendation: "MRI brain. Clinico-pathological correlation. Not for medico-legal purpose.", isNormal: false, sortOrder: 23,
    rows: [
      R("posterior_fossa_mass", "There is evidence of a pear shaped midline vermian mass (6.0 x 5.6 cm), displacing the fourth ventricle anteriorly. A thin crescent of CSF is seen. Cystic changes are seen within the mass. Post contrast scan shows homogeneous enhancement of the mass.", { inImpression: true }),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation and enhancement."),
      R("sulci", "Cortical sulci and sylvian fissures are effaced."),
      R("ventricles", "Grossly dilated third and bilateral lateral ventricles with periventricular oozing.", { inImpression: true }),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact. No obvious bony fracture is seen."),
    ],
  },
  {
    key: "ct-head-ependymoma", modality: "CT", region: "CT Head",
    name: "Posterior Fossa Mass ? Ependymoma", studyTitle: "NCCT BRAIN",
    titleSuffix: "posterior fossa mass",
    technique: T.ncct, recommendation: "Follow-up with CECT brain. MRI brain. Not for medico-legal purpose.", isNormal: false, sortOrder: 24,
    rows: [
      R("posterior_fossa_mass", "An ill defined infratentorial hyperdense homogenous mass arising from the floor of the 4th ventricle protruding within the lumen of ventricle medially, antero-laterally it is extending to the left cerebellopontine angle. Few tiny foci of calcification are seen within. No evidence of surrounding oedema or haemorrhage. No evidence of hydrocephalus.", { inImpression: true }),
      R("parenchyma", "Bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Rest of the posterior fossa structures are normal in attenuation."),
      R("sulci", "Cortical sulci and sylvian fissures are normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact."),
    ],
  },
  {
    key: "ct-head-porencephalic", modality: "CT", region: "CT Head",
    name: "Porencephalic Cyst / Schizencephaly", studyTitle: "NCCT BRAIN",
    titleSuffix: "porencephalic cyst",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 25,
    rows: [
      R("congenital", "Full thickness cleft in right occipital lobe extending from the occipital horn of right lateral ventricle to the surface of brain. Few foci of calcification adjacent to the cleft.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("sulci", "Rest of the cortical sulci and sylvian fissures are normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact. No obvious bony fracture is seen."),
    ],
  },
  {
    key: "ct-head-pneumocephalus", modality: "CT", region: "CT Head",
    name: "Pneumocephalus + Fractures", studyTitle: "NCCT BRAIN",
    titleSuffix: "pneumocephalus",
    technique: T.ncct, recommendation: "Clinico-pathological correlation.", isNormal: false, sortOrder: 26,
    rows: [
      R("pneumocephalus", "Hypodense areas of air density along the concavity of frontal bone — S/O Pneumocephalus.", { inImpression: true }),
      R("parenchyma", "Rest of the bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("sulci", "Cortical sulci and sylvian fissures are normal."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("fracture", "Fracture of the ethmoid and sphenoid bones and frontal bone in left supra-orbital region.", { inImpression: true }),
      R("soft_tissue", "Soft tissue swelling in bilateral periorbital, frontal and left temporo-parietal region.", { inImpression: true }),
    ],
  },
  {
    key: "ct-head-diffuse-oedema", modality: "CT", region: "CT Head",
    name: "Diffuse Cerebral Oedema + Scalp Oedema", studyTitle: "NCCT BRAIN",
    titleSuffix: "diffuse cerebral oedema",
    technique: T.ncct, recommendation: REC, isNormal: false, sortOrder: 27,
    rows: [
      R("soft_tissue", "Scalp oedema.", { inImpression: true }),
      R("oedema", "Bilateral diffuse cerebral oedema.", { inImpression: true }),
      R("parenchyma", "Bilateral cerebral hemispheres are normal in attenuation."),
      R("deep_gray", "Bilateral basal ganglia and thalamus are normal in attenuation."),
      R("posterior_fossa", "Posterior fossa structures are normal in attenuation."),
      R("sulci", "Cortical sulci and sylvian fissures are normal."),
      R("ventricles", "Ventricular system is normal."),
      R("midline", "Falx is central."),
      R("extra_axial", "There is no extra-axial collection."),
      R("calvarium", "Bony calvarium is intact."),
    ],
  },
];
