/**
 * MRI Brain pathology formats — curated from the doctor's own report
 * library. Verbatim clinical language, patient data stripped.
 */
import type { FormatSeed, FormatRowSeed } from "@/lib/seedData";

const T = {
  plain: "MRI brain performed using standard sequences: axial T1, T2, FLAIR, DWI, ADC and SWI. Images acquired on 3 Tesla scanner.",
  ce: "MRI brain performed on 3 Tesla scanner with standard multiplanar sequences before and after intravenous contrast.",
  ceTse: "T1W sagittal, DWI b0/b500/b1000, T2W axial, FLAIR coronal. Post-contrast T1 fat-suppressed images.",
};

const R = (
  concept: string,
  text: string,
  extra: Partial<FormatRowSeed> = {},
): FormatRowSeed => ({ region: "Brain", concept, text, inImpression: false, ...extra });

const IMP = (text: string): FormatRowSeed => ({
  region: "Brain", concept: "impression_summary", text,
  inImpression: true, impressionOnly: true,
});

export const MR_BRAIN_PATHOLOGY_FORMATS: FormatSeed[] = [
  {
    key: "mr-brain-acute-infarct", modality: "MR", region: "Brain",
    name: "Acute Infarct", studyTitle: "MRI BRAIN",
    titleSuffix: "acute infarct",
    technique: T.plain, recommendation: "Clinico-pathological correlation.",
    isNormal: false, sortOrder: 10,
    rows: [
      R("infarct", "Patchy T2/FLAIR hyperintensity showing DWI restriction noted in left capsuloganglionic region and left corona radiata — s/o acute infarct.", { inImpression: true }),
      R("atrophy", "Age-related enlargement of intra and extra-axial sulcal spaces noted — s/o cortico-cerebral atrophy.", { inImpression: true, newParagraph: true }),
      R("wmh", "Few tiny T2/FLAIR hyperintense signal changes seen in bilateral frontal and periventricular white matter — likely small vessel ischemic changes / non-specific.", { inImpression: true, newParagraph: true }),
      R("hippocampus", "No evidence of abnormal signal intensity or volume loss in the hippocampi.", { newParagraph: true }),
      R("basal_ganglia", "The thalami, basal ganglia and internal capsules are normal on the right side.", { newParagraph: true }),
      R("sella", "The pituitary gland, infundibulum and hypothalamus are normal for the age.", { newParagraph: true }),
      R("posterior_fossa", "The posterior fossa shows normal cerebellum. The medulla, pons and mid-brain show normal signals in all the sequences. Both CP angles are clear. The basal cisterns are normal.", { newParagraph: true }),
      R("vessels", "Normal flow void is seen in the major dural venous sinuses and arteries.", { newParagraph: true }),
    ],
  },
  {
    key: "mr-brain-chronic-infarct", modality: "MR", region: "Brain",
    name: "Chronic Infarct + Ischaemic Changes", studyTitle: "MRI BRAIN",
    titleSuffix: "chronic infarct and ischaemic changes",
    technique: T.plain, recommendation: "Clinico-pathological correlation.",
    isNormal: false, sortOrder: 11,
    rows: [
      R("infarct", "Infarct in bilateral periventricular region.", { inImpression: true }),
      R("ventricles", "Ventricular system & cisternal spaces, fissures & sulci are prominent — age-related changes.", { inImpression: true, newParagraph: true }),
      R("parenchyma", "Grey-white differentiation is well maintained.", { newParagraph: true }),
      R("posterior_fossa", "Region of brain stem and diencephalic areas are normal.", { newParagraph: true }),
      R("midline", "There is no midline shift. Cranio-cervical junction appears normal.", { newParagraph: true }),
    ],
  },
  {
    key: "mr-brain-lacunar-infarct", modality: "MR", region: "Brain",
    name: "Lacunar Infarct + Leukoaraiosis", studyTitle: "MRI BRAIN",
    titleSuffix: "lacunar infarct and small vessel disease",
    technique: T.plain, recommendation: "Clinico-pathological correlation.",
    isNormal: false, sortOrder: 12,
    rows: [
      R("infarct", "Lacunar infarct in bilateral basal ganglia region with age-related cortical atrophy.", { inImpression: true }),
      R("wmh", "Periventricular white matter hyperintensities are seen — leukoaraiosis / small vessel disease.", { inImpression: true, newParagraph: true }),
      R("ventricles", "Ventricular system is dilated. Cisternal spaces and cortical sulci are prominent.", { newParagraph: true }),
      R("parenchyma", "Grey-white differentiation is well maintained.", { newParagraph: true }),
      R("posterior_fossa", "Region of brain stem and diencephalic areas are normal.", { newParagraph: true }),
      R("midline", "There is no midline shift. Cranio-cervical junction appears normal.", { newParagraph: true }),
    ],
  },
  {
    key: "mr-brain-sdh-contusion", modality: "MR", region: "Brain",
    name: "Acute SDH + Contusion", studyTitle: "MRI BRAIN",
    titleSuffix: "acute subdural hemorrhage with contusion",
    technique: T.plain,
    recommendation: "CT for complete evaluation of bony skull vault. Not for medico-legal purpose.",
    isNormal: false, sortOrder: 13,
    rows: [
      R("hemorrhage", "Acute subdural hemorrhage of maximum thickness upto 4.4 mm seen along left fronto-temporo-parietal region showing hyperintense signals on T2 & FLAIR.", { inImpression: true }),
      R("contusion", "Hemorrhagic contusions with perifocal edema seen in left basitemporal region showing hyperintense signals on T1 sequences.", { inImpression: true, newParagraph: true }),
      R("parenchyma", "Elsewhere cerebral parenchyma appears normal.", { newParagraph: true }),
      R("basal_ganglia", "Bilateral basal ganglia and thalami are normal. Corpus callosum is normal in morphology and signal intensity.", { newParagraph: true }),
      R("posterior_fossa", "The brain stem and cerebellum appear normal.", { newParagraph: true }),
      R("midline", "No midline shift seen.", { newParagraph: true }),
      R("ventricles", "Both the lateral ventricles, the third and the fourth ventricles appear normal. Basal cisternal spaces appear normal.", { newParagraph: true }),
      R("sinuses", "T2 hyperintense mucosal thickening is noted in right maxillary sinus suggestive of sinusitis.", { newParagraph: true }),
    ],
  },
  {
    key: "mr-brain-edh", modality: "MR", region: "Brain",
    name: "Extradural Hematoma", studyTitle: "MRI BRAIN",
    titleSuffix: "extradural hematoma",
    technique: T.plain, recommendation: "Clinico-pathological correlation. Not for medico-legal purpose.",
    isNormal: false, sortOrder: 14,
    rows: [
      R("hemorrhage", "Extradural hematoma of thickness ~17.5 mm along right parietal lobe.", { inImpression: true }),
      R("scalp", "Scalp hematoma along right parieto-occipital lobes.", { inImpression: true, newParagraph: true }),
      R("wmh", "Few tiny patchy discrete hyperintensities are seen scattered in bilateral frontal and parietal subcortical as well as periventricular white matter, appearing iso to mildly hypointense on T1W images.", { inImpression: true, newParagraph: true }),
      R("parenchyma", "Rest of the brain parenchyma appears normal in signal intensity on all pulse sequences.", { newParagraph: true }),
      R("ventricles", "Ventricular system & cisternal spaces appear normal with normal fissures & sulci.", { newParagraph: true }),
      R("parenchyma_2", "Grey-white differentiation is well maintained. Region of brain stem and diencephalic areas are normal.", { newParagraph: true }),
      R("midline", "There is no midline shift. Cranio-cervical junction appears normal.", { newParagraph: true }),
    ],
  },
  {
    key: "mr-brain-contusion-midline-shift", modality: "MR", region: "Brain",
    name: "Hemorrhagic Contusion + Midline Shift", studyTitle: "MRI BRAIN",
    titleSuffix: "hemorrhagic contusion with midline shift",
    technique: T.plain,
    recommendation: "Serial neuroimaging (CT or MRI) to monitor for hematoma expansion or progression of perilesional edema. Clinical correlation for signs of elevated intracranial pressure (ICP).",
    isNormal: false, sortOrder: 15,
    rows: [
      R("contusion", "There is a well-defined intra-axial lesion within the left temporo-parietal parenchyma demonstrating heterogeneous signal, characterized by central T2/FLAIR hyperintensity and internal hypointense foci. Susceptibility-weighted imaging (SWI) reveals prominent blooming within the lesion, confirming an internal hemorrhagic component.", { inImpression: true }),
      R("edema", "Extensive surrounding vasogenic edema involving the left temporo-parietal white matter.", { inImpression: true, newParagraph: true }),
      R("midline", "The lesion and associated edema exert significant mass effect, resulting in a midline shift of approximately 5.7 mm at the level of the septum pellucidum, with complete effacement of the adjacent cortical sulci and narrowing of the sylvian fissure on the left.", { inImpression: true, newParagraph: true }),
      R("ventricles", "Significant compression and partial collapse of the ipsilateral lateral ventricle with mild compensatory prominence of the contralateral ventricle. No evidence of obstructive hydrocephalus or downward transtentorial herniation.", { newParagraph: true }),
      R("extraaxial", "No large-volume acute subdural or epidural hematoma is identified. The basal cisterns are narrowed but patent.", { newParagraph: true }),
      R("dwi", "No evidence of acute territorial infarction on DWI. Major intracranial flow voids are grossly preserved.", { newParagraph: true }),
      R("posterior_fossa", "The cerebellum and brainstem appear unremarkable in signal intensity and morphology. The cranio-cervical junction is intact.", { newParagraph: true }),
    ],
  },
  {
    key: "mr-brain-dai", modality: "MR", region: "Brain",
    name: "Diffuse Axonal Injury", studyTitle: "MRI BRAIN",
    titleSuffix: "diffuse axonal injury",
    technique: T.plain, recommendation: "Clinico-pathological correlation.",
    isNormal: false, sortOrder: 16,
    rows: [
      R("dai", "SWI/GRE sequences demonstrate small regions of susceptibility artifact (cerebral microbleeds) at the grey-white matter junction, in the corpus callosum, brainstem and scattered all over the brain parenchyma. Few focal areas of high FLAIR signal seen in left temporo-parietal region.", { inImpression: true }),
      R("basal_ganglia", "The basal nuclei, thalami and corpus callosum are showing normal signal intensity pattern.", { newParagraph: true }),
      R("ventricles", "Septum pellucidum and falx cerebri are in midline. No mass effect or midline shift is seen. Ventricular system & supratentorial sulcal and cisternal spaces normal. Fourth ventricle is normal in size and midline in position.", { newParagraph: true }),
      R("vessels", "Major intracranial dural venous sinuses are showing normal outline and flow void.", { newParagraph: true }),
      R("sella", "Sella, supra-sellar and para-sellar structures are normally visualized.", { newParagraph: true }),
      R("cpa", "Region of bilateral internal acoustic meatus and cerebellopontine angle are normal.", { newParagraph: true }),
    ],
  },
  {
    key: "mr-brain-meningioma", modality: "MR", region: "Brain",
    name: "Meningioma (CE)", studyTitle: "CE-MRI BRAIN",
    titleSuffix: "meningioma",
    technique: T.ce,
    recommendation: "MR spectroscopy or perfusion imaging if atypical features suspected. Clinico-pathological correlation.",
    isNormal: false, sortOrder: 17,
    rows: [
      R("mass", "A well-circumscribed, extra-axial mass lesion is identified in the right frontoparietal convexity, approximately 44.4 x 36.7 x 32.2 mm, globular in shape with well-defined margins. It is hypointense on T1, mildly hyperintense on T2 and isointense on FLAIR with a surrounding rim of perilesional edema. No diffusion restriction on DWI/ADC and no blooming on SWI. Post-contrast: brilliant homogeneous enhancement.", { inImpression: true }),
      R("dural_tail", "Broad dural attachment with dural tail sign — suggestive of dural origin.", { inImpression: true, newParagraph: true }),
      R("mass_effect", "Compression of adjacent sulci and gyri with effacement of ipsilateral sylvian fissure and compression of the ipsilateral lateral ventricle. Midline shift of approximately 6.3 mm towards the opposite side indicates significant mass effect. No invasion of adjacent brain parenchyma. No bone erosion or hyperostosis.", { inImpression: true, newParagraph: true }),
      R("other_lesions", "No additional intra- or extra-axial lesions identified. Ventricular system otherwise normal in size and configuration. Basal cisterns and posterior fossa structures are preserved. No abnormal meningeal thickening or enhancement.", { newParagraph: true }),
      R("sinuses", "Orbits, paranasal sinuses and mastoid air cells are unremarkable.", { newParagraph: true }),
      IMP("Brilliantly enhancing extra-axial mass lesion at the right frontoparietal convexity with perilesional edema and significant mass effect as described — imaging features suggestive of meningioma (likely WHO Grade I)."),
    ],
  },
  {
    key: "mr-brain-gbm", modality: "MR", region: "Brain",
    name: "High-Grade Glioma (GBM)", studyTitle: "CE-MRI BRAIN",
    titleSuffix: "high grade glioma",
    technique: T.ceTse, recommendation: "Histo-pathological correlation.",
    isNormal: false, sortOrder: 18,
    rows: [
      R("mass", "Ill-defined elongated altered signal intensity mass lesion with lobulated irregular margins involving subcortical and periventricular aspect of left temporo-parieto-occipital lobes, grossly measuring approx. 50 x 35 mm in axial plane and approx. 54 mm in craniocaudal extent.", { inImpression: true }),
      R("signal", "It appears homogeneously hypointense on T1W images, heterogeneously hyperintense on T2W and FLAIR images with few small cystic changes within it. Moderate perilesional edema is noted. It shows patchy areas of diffusion restriction on DWI/ADC images.", { newParagraph: true }),
      R("gre", "On GRE images, few foci of internal blooming seen — suggest possibility of intra-tumoral calcification / hemorrhage.", { newParagraph: true }),
      R("ce", "Post-contrast images show heterogeneous enhancement with central non-enhancing necrotic areas within it.", { newParagraph: true }),
      R("mass_effect", "It causes compression over adjacent left lateral ventricle and minimal midline shift of 3.7 mm towards right side.", { inImpression: true, newParagraph: true }),
      R("spect", "On MR spectroscopy study, there is evidence of increase in choline with decrease in NAA and increase in Cho/Cr ratio.", { newParagraph: true }),
      R("sinuses", "Changes of sinusitis are noted in bilateral maxillary sinuses.", { newParagraph: true }),
      R("basal_ganglia", "The thalami, basal ganglia and internal capsules are normal on both sides. No evidence of abnormal signal intensity or volume loss in the hippocampi. The pituitary gland, infundibulum and hypothalamus are normal for the age.", { newParagraph: true }),
      R("posterior_fossa", "The posterior fossa shows normal cerebellum. The medulla, pons and mid-brain show normal signals in all the sequences. Both CP angles are clear. The basal cisterns are normal.", { newParagraph: true }),
      R("vessels", "Normal flow void is seen in the major dural venous sinuses and arteries. Bones are normal.", { newParagraph: true }),
      IMP("Above findings are in favor of neoplastic etiology — high grade glioma / glioblastoma multiforme most likely."),
    ],
  },
  {
    key: "mr-brain-ncc", modality: "MR", region: "Brain",
    name: "Ring-Enhancing Granuloma (NCC/TB)", studyTitle: "CE-MRI BRAIN",
    titleSuffix: "ring enhancing granuloma",
    technique: T.ce,
    recommendation: "Clinical and laboratory correlation is recommended for definitive diagnosis. Suggested: MR spectroscopy for further characterization.",
    isNormal: false, sortOrder: 19,
    rows: [
      R("mass", "A solitary, sharply demarcated hypointense lesion is identified in left high parietal lobe on T1-weighted images, demonstrating characteristic ring enhancement on post-contrast T1W images. Significant perilesional edema is evident surrounding the lesion, appearing hyperintense on T2W and FLAIR sequences.", { inImpression: true }),
      R("ventricles", "The ventricular system and basal cisterns are normal in size and configuration.", { newParagraph: true }),
      R("midline", "There is no evidence of midline shift. Gray-white matter differentiation is preserved.", { newParagraph: true }),
      R("parenchyma", "The fissures and sulci are within normal limits. The brainstem, diencephalic structures and cranio-cervical junction show normal morphology and signal intensity.", { newParagraph: true }),
      IMP("Solitary ring-enhancing lesion with significant perilesional edema in the left high parietal lobe. Imaging features are highly suggestive of an infectious or inflammatory granuloma — differential diagnosis: neurocysticercosis (NCC) / tuberculoma."),
    ],
  },
  {
    key: "mr-brain-ms", modality: "MR", region: "Brain",
    name: "Demyelinating Disease (MS)", studyTitle: "MRI BRAIN WITH CONTRAST",
    titleSuffix: "demyelinating plaques",
    technique: T.ceTse, recommendation: "Please correlate with clinical findings.",
    isNormal: false, sortOrder: 20,
    rows: [
      R("wmh", "Multiple confluent and discrete hyperintense foci in FLAIR / T2 weighted images are seen perpendicular in the bilateral fronto-parietal, bilateral corona radiata and occipital periventricular white matter.", { inImpression: true }),
      R("ce", "No evidence of abnormal meningeal / parenchymal enhancement seen on post-contrast study.", { newParagraph: true }),
      R("parenchyma", "Rest of the cerebral hemispheres show normal MR morphology, signal intensity and gray-white matter differentiation.", { newParagraph: true }),
      R("ventricles", "Both lateral ventricles and third ventricle are normal in size, shape and outline. Septum pellucidum and falx cerebri are in midline. No mass effect or midline shift is seen. Supratentorial sulcal and cisternal spaces are normally visualized.", { newParagraph: true }),
      R("posterior_fossa", "Brain stem and cerebellar hemispheres are showing normal morphology, signal intensity and outline. Fourth ventricle is normal in size and midline in position.", { newParagraph: true }),
      R("vessels", "Major intracranial dural venous sinuses are showing normal outline and flow void.", { newParagraph: true }),
      R("sella", "Sella, supra-sellar and para-sellar structures are normally visualized. Region of bilateral internal acoustic meatus and cerebellopontine angle are normal.", { newParagraph: true }),
      IMP("MR findings reveal multiple confluent and discrete hyperintense foci perpendicular in the bilateral fronto-parietal, corona radiata and occipital periventricular white matter — suggestive of demyelinating plaques. To consider the possibility of multiple sclerosis."),
    ],
  },
  {
    key: "mr-brain-hydrocephalus", modality: "MR", region: "Brain",
    name: "Hydrocephalus (Non-Communicating)", studyTitle: "MRI BRAIN",
    titleSuffix: "hydrocephalus",
    technique: "MRI brain performed using T1 & T2 axial & coronal, T1 sagittal and T2 FLAIR sequences.",
    recommendation: "Clinico-pathological correlation.",
    isNormal: false, sortOrder: 21,
    rows: [
      R("ventricles", "Evidence of dilated bilateral lateral and 3rd ventricles with effaced bilateral cortical sulci, sylvian fissure and cisterns.", { inImpression: true }),
      R("parenchyma", "Evidence of generalized cerebral compression. Supratentorial brain parenchyma appears normal. No focal lesion is seen. Centrum semiovale and white matter tracts are normal.", { inImpression: true, newParagraph: true }),
      R("corpus_callosum", "Corpus callosum is normal in size and shape with normal signal intensity.", { newParagraph: true }),
      R("basal_ganglia", "The basal ganglia and thalami appear normal.", { newParagraph: true }),
      R("midline", "No shift of midline structures is seen.", { newParagraph: true }),
      R("posterior_fossa", "The brainstem and cerebellum appear normal.", { newParagraph: true }),
      R("sella", "Sella and pituitary gland are normal.", { newParagraph: true }),
      R("vessels", "Intracranial vessels display normal flow void. The visualized orbits and paranasal sinuses are normal.", { newParagraph: true }),
    ],
  },
  {
    key: "mr-brain-hie", modality: "MR", region: "Brain",
    name: "HIE (Pediatric)", studyTitle: "MRI BRAIN",
    titleSuffix: "hypoxic ischemic encephalopathy",
    technique: "T1W sagittal, DWI b0/b500/b1000, T2W axial, FLAIR coronal.",
    recommendation: "Correlate with clinical history focusing on perinatal events, developmental milestones and neurological examination. Recommend follow-up MRI in 6-12 months to assess progression or stability of white matter changes.",
    isNormal: false, sortOrder: 22,
    rows: [
      R("parenchyma", "Evidence of T2W hyperintensity (CSF signal in all sequences) in bilateral fronto-parietal lobes and bilateral insular cortex with ex-vacuo dilatation of bilateral lateral ventricles.", { inImpression: true }),
      R("infarct", "No evidence of acute infarct, hemorrhage or space-occupying mass lesion noted.", { newParagraph: true }),
      R("basal_ganglia", "The thalami, basal ganglia and internal capsules are normal on both sides.", { newParagraph: true }),
      R("ventricles", "The ventricles and sulci are normal for the age.", { newParagraph: true }),
      R("sella", "The pituitary gland, infundibulum and hypothalamus are normal for the age.", { newParagraph: true }),
      R("posterior_fossa", "The posterior fossa shows normal cerebellum. The medulla, pons and mid-brain show normal signals in all the sequences. Both CP angles are clear. The basal cisterns are normal.", { newParagraph: true }),
      R("vessels", "Normal flow void is seen in the major dural venous sinuses and arteries.", { newParagraph: true }),
      IMP("Evidence of T2W hyperintensity (CSF signal in all sequences) in bilateral fronto-parietal lobes and bilateral insular cortex with ex-vacuo dilatation of bilateral lateral ventricles. D/D — hypoxic ischemic encephalopathy."),
    ],
  },
  {
    key: "mr-brain-arachnoid", modality: "MR", region: "Brain",
    name: "Arachnoid Cyst", studyTitle: "MRI BRAIN (PRE & POST GADOLINIUM)",
    titleSuffix: "arachnoid cyst",
    technique: T.ce,
    recommendation: "Clinical correlation is advised. Follow-up imaging in 6-12 months may be considered to ensure interval stability.",
    isNormal: false, sortOrder: 23,
    rows: [
      R("mass", "A well-defined, rounded, extra-axial cystic lesion is noted in right occipital parasagittal region, closely abutting the inner table of the skull and the posterior falx, measuring approximately 18 x 17 mm in its maximum axial dimensions with a craniocaudal extent of ~25 mm.", { inImpression: true }),
      R("signal", "Signal characteristics — T1W/T2W: follows CSF signal intensity. FLAIR: complete suppression of internal signal. DWI/ADC: no evidence of restricted diffusion. SWI: no internal blooming. Post-contrast: subtle, thin peripheral wall enhancement. No associated perilesional edema or significant mass effect.", { newParagraph: true }),
      R("parenchyma", "The remainder of the cerebral parenchyma shows normal signal intensity and morphology. No evidence of acute infarct, hemorrhage or space-occupying lesion elsewhere.", { newParagraph: true }),
      R("ventricles", "The lateral, third and fourth ventricles are normal in size, shape and configuration. No evidence of obstructive hydrocephalus.", { newParagraph: true }),
      R("midline", "The septum pellucidum and falx cerebri are midline. No midline shift or herniation.", { newParagraph: true }),
      R("posterior_fossa", "The cerebellum and brainstem appear normal. The CP angles and internal auditory canals are unremarkable.", { newParagraph: true }),
      R("extraaxial", "Apart from the aforementioned lesion, the basal cisterns and cortical sulci are within normal limits. No other extra-axial collections. Major intracranial vascular flow voids are preserved.", { newParagraph: true }),
      IMP("Well-defined cystic lesion in the right occipital parasagittal (extra-axial/parafalcine) region with CSF-like signal on all sequences including FLAIR suppression and lack of diffusion restriction — most likely arachnoid cyst. Differential: neuroglial cyst (epidermoid unlikely — no restricted diffusion)."),
    ],
  },
  {
    key: "mr-brain-atrophy", modality: "MR", region: "Brain",
    name: "Cerebral Atrophy (Senile Changes)", studyTitle: "MRI BRAIN",
    titleSuffix: "senile changes",
    technique: T.plain,
    recommendation: "Clinical correlation. Follow-up study if clinically indicated.",
    isNormal: false, sortOrder: 24,
    rows: [
      R("atrophy", "There is evidence of mild generalized brain volume loss, characterized by prominence of the supratentorial cortical sulci and extra-axial CSF spaces for age.", { inImpression: true }),
      R("parenchyma", "Grey-white matter differentiation is normal. Myelination pattern is appropriate for age.", { newParagraph: true }),
      R("ventricles", "The lateral, third and fourth ventricles are symmetric and mildly prominent ex-vacuo secondary to the volume loss, without evidence of obstructive hydrocephalus.", { inImpression: true, newParagraph: true }),
      R("midline", "The corpus callosum is intact. The septum pellucidum is in the midline. No mass lesion or midline shift.", { newParagraph: true }),
      R("posterior_fossa", "The cerebellum and brainstem appear normal in morphology and signal intensity.", { newParagraph: true }),
      R("sinuses", "Visualized orbital contents are unremarkable. Imaged paranasal sinuses and mastoid air cells appear clear.", { newParagraph: true }),
      R("mass", "No evidence of focal space-occupying lesion (SOL), acute infarct or intracranial hemorrhage.", { newParagraph: true }),
    ],
  },
  {
    key: "mr-brain-cp-angle", modality: "MR", region: "Brain",
    name: "CP Angle Tumor", studyTitle: "MRI BRAIN",
    titleSuffix: "cp angle tumor",
    technique: "MRI brain performed using T1, T2 & FLAIR axial, T1 sagittal and T2 coronal sections.",
    recommendation: "Clinico-pathological correlation / audiometry.",
    isNormal: false, sortOrder: 25,
    rows: [
      R("mass", "There is a well-defined space-occupying lesion in right cerebellopontine angle centering on the internal acoustic meatus. The mass is slightly hypointense to the adjacent brain on T1WI and heterogeneously hyperintense on T2WI, with intense post-contrast enhancement. It is causing mass effect and compressing the brainstem, pushing the IVth ventricle to the contralateral side and causing hydrocephalus.", { inImpression: true }),
      R("basal_ganglia", "The basal nuclei, thalami and corpus callosum are showing normal signal intensity pattern.", { newParagraph: true }),
      R("parenchyma", "Grey-white differentiation is well maintained.", { newParagraph: true }),
      R("sella", "Sella, supra-sellar and para-sellar structures are normally visualized.", { newParagraph: true }),
      R("vessels", "Major intracranial dural venous sinuses are showing normal outline and flow void.", { newParagraph: true }),
      R("midline", "Cranio-cervical junction appears normal.", { newParagraph: true }),
      IMP("Well-defined space-occupying tumor in right CP angle with mass effect and hydrocephalus. D/D — acoustic schwannoma / meningioma."),
    ],
  },
];
