/**
 * USG Whole Abdomen / Upper Abdomen complete-report formats — curated
 * verbatim from the doctor's own USG library (docs/report-formats/usg).
 *
 * Structure is the doctor's organ-slot scaffold: one FindingRow per organ
 * (LIVER / G.B / C.B.DUCT / PANCREAS / SPLEEN / KIDNEYS / URETERS / U.B /
 * PROSTATE|UTERUS+ADNEXA / R.I.F / OTHERS). Pathology formats replace the
 * affected organ's slot and add impression lines — so phrase chips and
 * additional formats still compose on top (slot replacement).
 *
 * Medico-legal rule: every measurement is a fill-in blank ("___ cm"),
 * never a sample value. Normal formats carry NO blanks — one tap prints.
 */
import type { FormatSeed, FormatRowSeed } from "@/lib/seedData";

const REC = "Kindly co-relate with clinico-pathological findings.";

const row = (concept: string, text: string, extra: Partial<FormatRowSeed> = {}): FormatRowSeed => ({
  region: "USG Whole Abdomen", concept, text, inImpression: false, ...extra,
});

const NI = (text = "No significant abnormality detected."): FormatRowSeed => ({
  region: "USG Whole Abdomen", concept: "normal_impression", text,
  inImpression: true, impressionOnly: true,
});

// ── The doctor's normal organ lines (verbatim) ─────────────────────────────
const LIVER_N = "Liver appears normal in morphology and parenchymal echogenicity. No masses or focal pathology is noted. Intrahepatic biliary channels are not dilated. The portal vein is normal in appearance.";
const GB_N = "Gall bladder is normal in physiological distension. No calculi or other intrinsic lesions are noted. Wall thickness is normal. No pericholecystic collection. Sonographic Murphy's sign negative.";
const CBD_N = "Diameter of the C.B.D is normal. No evidence of intraluminal calculus.";
const PANCREAS_N = "Pancreas appears normal in morphology and parenchymal echogenicity. Pancreatic duct is not dilated. No evidence of calcification or focal lesion is seen.";
const SPLEEN_N = "Spleen appears normal in morphology and parenchymal echogenicity. No evidence of focal lesion or S.O.L seen. No evidence of splenic collateral vessels.";
const KIDNEY_N = "Normal in shape, size & position. Sinuses as well as cortical echoes are normal. No evidence of calculus, space occupying lesion, cyst or hydronephrosis is seen.";
const URETERS_N = "Proximal and distal ureters are normal.";
const UB_N = "Urinary bladder is normal in outline and distension. It is echo free. No evidence of calculus, mass or diverticulum is seen. Insignificant post void residual urine.";
const PROSTATE_N = "Prostate is normal in size and echotexture. It is echo free. No evidence of focal lesion or S.O.L noted.";
const RIF_N = "No obvious mass lesion is seen.";
const OTHERS_N = "No free peritoneal fluid / enlarged lymph nodes are seen.";
const UTERUS_N = "Uterus is normal in size and shape. The uterus is in anteversion with normal endometrial thickness. No focal pathology or abnormalities of outline are noted. The cervical echo is normal.";
const ADNEXA_N = "Ovaries are normally positioned. Normal in echotexture.";
const POD_N = "Pouch of Douglas is clear.";

const T_WA = "Ultrasonography of the whole abdomen was performed in supine position using a curvilinear 3.5 MHz transducer.";
const T_UA = "Ultrasonography of the upper abdomen was performed in supine position using a curvilinear 3.5 MHz transducer.";

export const USG_ABDOMEN_FORMATS: FormatSeed[] = [
  // ── Base scaffolds ────────────────────────────────────────────────────────
  {
    key: "usg-wa-male-normal", modality: "USG", region: "USG Whole Abdomen",
    name: "Normal — Male", studyTitle: "USG WHOLE ABDOMEN", titleSuffix: "",
    technique: T_WA, recommendation: REC, isNormal: true, sortOrder: 1,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
      NI(),
    ],
  },
  {
    key: "usg-wa-female-normal", modality: "USG", region: "USG Whole Abdomen",
    name: "Normal — Female", studyTitle: "USG WHOLE ABDOMEN", titleSuffix: "",
    technique: T_WA, recommendation: REC, isNormal: true, sortOrder: 2,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("uterus", UTERUS_N),
      row("adnexa", ADNEXA_N),
      row("pod", POD_N),
      row("others", OTHERS_N),
      NI(),
    ],
  },
  {
    key: "usg-wa-gas-fluid", modality: "USG", region: "USG Whole Abdomen",
    name: "Gaseous + Fluid & Faeces Loops", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "gaseous abdomen with fluid and faeces filled bowel loops",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 3,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", "Excessive bowel gas shadow. Fluid and faeces filled bowel loops.", { inImpression: true }),
      row("others", "No free peritoneal fluid / enlarged lymph nodes are seen."),
    ],
  },
  {
    key: "usg-upper-normal", modality: "USG", region: "USG Whole Abdomen",
    name: "Normal — Upper Abdomen", studyTitle: "USG UPPER ABDOMEN", titleSuffix: "",
    technique: T_UA, recommendation: REC, isNormal: true, sortOrder: 4,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("others", OTHERS_N),
      NI("Normal scan of upper abdomen."),
    ],
  },

  // ── Hepatobiliary ─────────────────────────────────────────────────────────
  {
    key: "usg-fatty-liver-g1", modality: "USG", region: "USG Whole Abdomen",
    name: "Fatty Liver — Grade I", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "grade i fatty changes",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 10,
    rows: [
      row("liver", "Liver is enlarged in size and measures in mid-clavicular line ___ cm. Appears normal in morphology with mildly increased hepatic parenchymal echogenicity (Grade I fatty changes). No masses or focal pathology is noted. Intrahepatic biliary channels are not dilated. The portal vein is normal in appearance.", { inImpression: true }),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", "Excessive bowel gas shadow is seen in the abdominal cavity.", { inImpression: true }),
    ],
  },
  {
    key: "usg-fatty-liver-g2", modality: "USG", region: "USG Whole Abdomen",
    name: "Fatty Liver — Grade II", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "grade ii fatty changes",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 11,
    rows: [
      row("liver", "Liver is enlarged in size and measures in mid-clavicular line ___ cm. Shows moderately increased hepatic parenchymal echogenicity with mild attenuation and blurring of the portal vein radicles (Grade II fatty changes). No masses or focal pathology is noted. Intrahepatic biliary channels are not dilated.", { inImpression: true }),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-cholelithiasis", modality: "USG", region: "USG Whole Abdomen",
    name: "Cholelithiasis", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "cholelithiasis",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 12,
    rows: [
      row("liver", LIVER_N),
      row("gb", "Gall bladder is normal in physiological distension. A well defined echogenic structure (___ cm) casting strong distal acoustic shadow is seen in the lumen of the gall bladder, suggestive of calculus. Wall thickness is normal. No pericholecystic collection. Sonographic Murphy's sign negative.", { inImpression: true }),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-cholecystitis", modality: "USG", region: "USG Whole Abdomen",
    name: "Cholecystitis (Thickened GB Wall)", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "cholecystitis",
    technique: T_WA, recommendation: "Follow up scan. " + REC, isNormal: false, sortOrder: 13,
    rows: [
      row("liver", LIVER_N),
      row("gb", "Gall bladder is normal in physiological distension. No calculi are noted. GB wall is thickened and oedematous with maximum thickness of ___ cm in the fundal region with positive sonographic Murphy's sign, S/o Cholecystitis. No pericholecystic collection.", { inImpression: true }),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-gb-polyp", modality: "USG", region: "USG Whole Abdomen",
    name: "GB Polyp", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "gall bladder polyp",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 14,
    rows: [
      row("liver", LIVER_N),
      row("gb", "Gall bladder is normal in physiological distension. A small echogenic polyp attached to the anterior wall (___ x ___ cm). No evidence of intraluminal calculus. Wall thickness is normal. No pericholecystic collection. Sonographic Murphy's sign negative.", { inImpression: true }),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-choledocholithiasis", modality: "USG", region: "USG Whole Abdomen",
    name: "Choledocholithiasis (CBD Calculus)", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "choledocholithiasis",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 15,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", "C.B.D is dilated and measures ___ cm in diameter. A well defined echogenic focus (___ cm) casting strong distal acoustic shadow is seen in the distal part of the C.B.D, S/o Choledocholithiasis.", { inImpression: true }),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-cbd-dilated", modality: "USG", region: "USG Whole Abdomen",
    name: "CBD Dilated (Distal Not Evaluated)", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "dilated cbd",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 16,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", "C.B.D is dilated and measures ___ cm in diameter. No evidence of intraluminal calculus. The most distal part of the C.B.D could not be evaluated due to overlying bowel gas.", { inImpression: true }),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-liver-abscess", modality: "USG", region: "USG Whole Abdomen",
    name: "Liver Abscess", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "liver abscess",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 17,
    rows: [
      row("liver", "Liver is enlarged in size and measures in mid-clavicular line ___ cm. A well defined hypoechoic lesion (___ x ___ cm) with thick irregular walls and internal debris is seen in the right lobe of liver, S/o Liver abscess. Rest of the hepatic parenchyma shows normal echogenicity. Intrahepatic biliary channels are not dilated.", { inImpression: true }),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", "No free peritoneal fluid / enlarged lymph nodes are seen."),
    ],
  },
  {
    key: "usg-hemangioma", modality: "USG", region: "USG Whole Abdomen",
    name: "Hepatic Haemangioma", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "hepatic haemangioma",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 18,
    rows: [
      row("liver", "Liver appears normal in morphology and parenchymal echogenicity. A well defined hyperechoic lesion (___ x ___ cm) with homogeneous echotexture is seen in the right lobe of liver, S/o Haemangioma. No masses or focal pathology elsewhere. Intrahepatic biliary channels are not dilated. The portal vein is normal in appearance.", { inImpression: true }),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-portal-cavernosa", modality: "USG", region: "USG Whole Abdomen",
    name: "Portal Cavernoma / Portal Hypertension", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "portal cavernoma with portal hypertension",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 19,
    rows: [
      row("liver", "Liver appears normal in morphology and parenchymal echogenicity. The portal vein measures ___ cm. Dilated and tortuous vessels are seen at the portal confluence, S/o Portal cavernoma. Intrahepatic biliary channels are not dilated.", { inImpression: true }),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", "Spleen is enlarged and measures ___ cm in length. Appears normal in morphology and parenchymal echogenicity. Evidence of splenic collateral vessels is seen.", { inImpression: true }),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("others", "Mild free peritoneal fluid is seen.", { inImpression: true }),
    ],
  },
  {
    key: "usg-pancreatitis-acute", modality: "USG", region: "USG Whole Abdomen",
    name: "Acute Pancreatitis", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "acute pancreatitis",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 20,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", "Pancreas appears bulky and heterogenous in echotexture with reduced parenchymal echogenicity. Peripancreatic fluid collection is seen. Pancreatic duct is not dilated.", { inImpression: true }),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("others", "Excessive bowel gas shadow is seen in the abdominal cavity."),
    ],
  },
  {
    key: "usg-pancreatitis-chronic", modality: "USG", region: "USG Whole Abdomen",
    name: "Chronic Pancreatitis (Dilated PD)", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "chronic pancreatitis",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 21,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", "Pancreas appears reduced in size with increased parenchymal echogenicity and irregular outline. Pancreatic duct is dilated and measures ___ cm, with evidence of intraductal calcification. No peripancreatic collection seen.", { inImpression: true }),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("others", OTHERS_N),
    ],
  },

  // ── Renal / urinary ──────────────────────────────────────────────────────
  {
    key: "usg-nephrolith", modality: "USG", region: "USG Whole Abdomen",
    name: "Renal Calculus", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "renal calculus",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 30,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney is normal in shape, size & position. A well defined echogenic focus (___ cm) casting strong distal acoustic shadow is seen at the ___ of the right kidney, S/o calculus. No hydronephrosis.", { inImpression: true }),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-nephrolith-bilateral", modality: "USG", region: "USG Whole Abdomen",
    name: "Bilateral Nephrolithiasis", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "bilateral nephrolithiasis",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 31,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney is normal in shape, size & position. Sinuses as well as cortical echoes are normal. A small echogenic focus (___ cm) at the ___ calyx of the right kidney, casting strong distal acoustic shadow, S/o calculus. No hydronephrosis.", { inImpression: true }),
      row("kidneys_lt", "Left kidney is normal in shape, size & position. Sinuses as well as cortical echoes are normal. A small echogenic focus (___ cm) at the ___ of the left kidney, casting strong distal acoustic shadow, S/o calculus. No hydronephrosis.", { inImpression: true }),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-vuj-calculus", modality: "USG", region: "USG Whole Abdomen",
    name: "VUJ Calculus with HUN", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "vuj calculus with hydroureteronephrosis",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 32,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney is normal in shape, size & position. Left pelvicalyceal system is mildly dilated.", { inImpression: true }),
      row("ureters", "A well defined echogenic focus (___ cm), casting strong distal acoustic shadow is seen at the left vesico-ureteric junction. Left ureter is dilated upto the calculus.", { inImpression: true }),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-distal-ureteric-calculus", modality: "USG", region: "USG Whole Abdomen",
    name: "Distal Ureteric Calculus", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "distal ureteric calculus",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 33,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney is normal in shape, size & position. Left pelvicalyceal system is mildly dilated.", { inImpression: true }),
      row("ureters", "A well defined echogenic focus (___ cm), casting strong distal acoustic shadow is seen in the left distal ureter. Left ureter is dilated upto the calculus.", { inImpression: true }),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-renal-cyst", modality: "USG", region: "USG Whole Abdomen",
    name: "Renal Cortical Cyst", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "renal cortical cyst",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 34,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney is normal in shape, size & position. A well defined simple cortical cyst (___ x ___ cm) with thin wall and clear content is seen at the ___ pole of the right kidney. No internal echoes or septa. No calculus or hydronephrosis.", { inImpression: true }),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-pckd", modality: "USG", region: "USG Whole Abdomen",
    name: "Polycystic Kidney Disease", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "polycystic kidney disease",
    technique: T_WA, recommendation: "Renal function test advised. " + REC, isNormal: false, sortOrder: 35,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Both kidneys are enlarged, maintaining their reniform shape with generalized increased echogenicity. Numerous cysts of various sizes are scattered throughout the parenchyma of both kidneys. Right kidney measures ___ cm.", { inImpression: true }),
      row("kidneys_lt", "Left kidney measures ___ cm. Same picture as right — multiple cysts of varying sizes with increased parenchymal echogenicity.", { inImpression: true }),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-puj-calculus", modality: "USG", region: "USG Whole Abdomen",
    name: "PUJ Calculus with Hydronephrosis", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "puj calculus with hydronephrosis",
    technique: T_WA, recommendation: "X-Ray KUB suggested. " + REC, isNormal: false, sortOrder: 36,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney is normal in shape, size & position. Left pelvicalyceal system is dilated. A well defined echogenic focus (___ cm), casting strong distal acoustic shadow is seen at the left pelvi-ureteric junction.", { inImpression: true }),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-renal-parenchymal", modality: "USG", region: "USG Whole Abdomen",
    name: "Medical Renal Disease", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "medical renal disease",
    technique: T_WA, recommendation: "Renal function test advised. " + REC, isNormal: false, sortOrder: 37,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney is normal in shape and position. Increased renal parenchymal echogenicity with loss of cortico-medullary differentiation. No calculus or hydronephrosis.", { inImpression: true }),
      row("kidneys_lt", "Left kidney shows the same increased parenchymal echogenicity with loss of cortico-medullary differentiation. No calculus or hydronephrosis.", { inImpression: true }),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },

  // ── Bladder / prostate ───────────────────────────────────────────────────
  {
    key: "usg-cystitis", modality: "USG", region: "USG Whole Abdomen",
    name: "Cystitis (Thickened UB Wall)", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "cystitis",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 40,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", "Urinary bladder is partially distended. Thickened U.B wall. No evidence of calculus, mass or diverticulum is seen. Insignificant post void residual urine.", { inImpression: true }),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-prostatomegaly", modality: "USG", region: "USG Whole Abdomen",
    name: "Prostatomegaly (Grade II)", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "prostatomegaly",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 41,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("prostate", "Prostate is enlarged in size and measures ___ X ___ X ___ cm, corresponding to ___ gms (Grade II prostatomegaly). Median lobe is protruding into the urinary bladder base. No evidence of focal lesion or S.O.L noted.", { inImpression: true }),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },
  {
    key: "usg-ub-calculus", modality: "USG", region: "USG Whole Abdomen",
    name: "UB Calculus", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "urinary bladder calculus",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 42,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", "Urinary bladder is normal in outline and distension. A well defined echogenic focus (___ cm) casting strong distal acoustic shadow is seen in the urinary bladder, S/o calculus. No evidence of mass or diverticulum. Insignificant post void residual urine.", { inImpression: true }),
      row("prostate", PROSTATE_N),
      row("rif", RIF_N),
      row("others", OTHERS_N),
    ],
  },

  // ── Appendix / RIF / bowel ───────────────────────────────────────────────
  {
    key: "usg-acute-appendicitis", modality: "USG", region: "USG Whole Abdomen",
    name: "Acute Appendicitis", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "acute appendicitis",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 50,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("rif", "A tubular, non-compressible, blind-ended structure with target configuration is seen in the right iliac fossa, measuring ___ cm in length and ___ cm in diameter. Wall is thickened with increased surrounding echogenicity of mesenteric fat. Strong probe tenderness present in right iliac fossa, S/o Acute Appendicitis.", { inImpression: true }),
      row("others", "No free peritoneal fluid / enlarged lymph nodes are seen."),
    ],
  },
  {
    key: "usg-appendicular-lump", modality: "USG", region: "USG Whole Abdomen",
    name: "Appendicular Lump", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "appendicular lump",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 51,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("rif", "A heterogeneous, ill-defined mass lesion (___ x ___ cm) with hypoechoic centre is seen in the right iliac fossa with strong probe tenderness, S/o Appendicular lump with abscess formation. Few enlarged mesenteric lymph nodes are seen in the surrounding region.", { inImpression: true }),
      row("others", "No free peritoneal fluid is seen."),
    ],
  },
  {
    key: "usg-mesenteric-nodes", modality: "USG", region: "USG Whole Abdomen",
    name: "Mesenteric Lymphadenopathy", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "mesenteric lymphadenopathy",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 52,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("rif", "No obvious mass lesion is seen."),
      row("others", "Few enlarged mesenteric lymph nodes (largest ___ x ___ cm) are seen in the right iliac fossa / peri-umbilical region.", { inImpression: true }),
    ],
  },
  {
    key: "usg-intestinal-obstruction", modality: "USG", region: "USG Whole Abdomen",
    name: "Intestinal Obstruction", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "intestinal obstruction",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 53,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("others", "Multiple distended bowel loops with prominent valvulae conniventes are seen in the central abdomen. Increased peristaltic movement is seen in the proximal loops. X-ray abdomen erect suggested.", { inImpression: true }),
    ],
  },

  // ── Paediatric abdomen ───────────────────────────────────────────────────
  {
    key: "usg-intussusception", modality: "USG", region: "USG Whole Abdomen",
    name: "Intussusception (Child)", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "intussusception",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 60,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("others", "Bowel within bowel appearance with positive doughnut sign is seen in the right lower quadrant with strong probe tenderness, S/o Intussusception (Ilio-caecal type).", { inImpression: true }),
    ],
  },
  {
    key: "usg-chps", modality: "USG", region: "USG Whole Abdomen",
    name: "CHPS — Pyloric Stenosis (Child)", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "congenital hypertrophic pyloric stenosis",
    technique: T_WA, recommendation: "Follow up scan. " + REC, isNormal: false, sortOrder: 61,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("others", "Elongated pyloric canal with thickened wall. No peristaltic movements through the canal. Canal length ___ cm & canal diameter ___ cm. No enlarged mesenteric lymph nodes or intraperitoneal collection.", { inImpression: true }),
    ],
  },
  {
    key: "usg-umbilical-hernia", modality: "USG", region: "USG Whole Abdomen",
    name: "Umbilical Hernia", studyTitle: "USG WHOLE ABDOMEN",
    titleSuffix: "umbilical hernia",
    technique: T_WA, recommendation: REC, isNormal: false, sortOrder: 62,
    rows: [
      row("liver", LIVER_N),
      row("gb", GB_N),
      row("cbd", CBD_N),
      row("pancreas", PANCREAS_N),
      row("spleen", SPLEEN_N),
      row("kidneys", "Right kidney: " + KIDNEY_N),
      row("kidneys_lt", "Left kidney: " + KIDNEY_N),
      row("ureters", URETERS_N),
      row("ub", UB_N),
      row("others", "A defect (___ cm) is seen in the umbilical region with herniation of bowel loops / omental fat through it, S/o Umbilical hernia. Content is reducible on probe pressure.", { inImpression: true }),
    ],
  },

  // ── USG chest / miscellaneous ────────────────────────────────────────────
  {
    key: "usg-pleural-effusion", modality: "USG", region: "USG Whole Abdomen",
    name: "Pleural Effusion", studyTitle: "USG CHEST",
    titleSuffix: "pleural effusion",
    technique: "Ultrasonography of the chest was performed in sitting position using a curvilinear 3.5 MHz transducer.",
    recommendation: REC, isNormal: false, sortOrder: 70,
    rows: [
      row("effusion", "Anechoic fluid collection is seen in the right pleural cavity, measuring ___ cm in maximum depth with collapse of the underlying lung parenchyma. No septations or internal echoes seen.", { inImpression: true }),
      row("lung", "The underlying lung shows reduced movements with the breathing cycle."),
      row("diaphragm", "The right dome of diaphragm is elevated and its movements are restricted."),
      row("left", "Left pleural cavity is clear. No fluid collection seen."),
    ],
  },
  {
    key: "usg-soft-tissue-abscess", modality: "USG", region: "USG Whole Abdomen",
    name: "Soft-Tissue Abscess", studyTitle: "USG SOFT TISSUE",
    titleSuffix: "soft tissue abscess",
    technique: "High frequency (7.5-10 MHz) linear transducer was used to evaluate the palpable swelling.",
    recommendation: REC, isNormal: false, sortOrder: 71,
    rows: [
      row("lesion", "A well defined hypoechoic collection (___ x ___ cm) with thick irregular walls and internal debris is seen in the subcutaneous plane of the palpable swelling, S/o Abscess. Increased surrounding soft tissue echogenicity is noted.", { inImpression: true }),
      row("doppler", "On colour doppler, increased peripheral vascularity is seen around the lesion."),
      row("deeper", "Deeper muscular planes appear normal. No underlying bone erosion seen."),
    ],
  },
];
